import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import Head from 'next/head';

const PAGE_CSS = `
  :root{--ink:#17214f;--muted:#7580a6;--bg:#f5f6ff;--line:#e5e8fb;--a1:#5668ff;--a2:#7446e8;--soft:#f2f1ff;--green:#16a34a}
  *{box-sizing:border-box} body{margin:0;font-family:'Segoe UI',system-ui,-apple-system,sans-serif;background:linear-gradient(135deg,#f8f9ff 0%,#f1f2ff 100%);color:var(--ink)}
  button,a{font:inherit}.es-page{min-height:100vh;padding:34px 28px 48px}.topbar{max-width:1180px;margin:0 auto 38px;display:flex;align-items:center;justify-content:space-between;gap:18px}.brand{display:flex;align-items:center;gap:12px}.brand img{height:44px}.brand-text h2{margin:0;font-size:19px}.brand-text p{margin:2px 0 0;color:var(--muted);font-size:12.5px}.top-actions{display:flex;gap:10px}.top-btn{display:inline-flex;align-items:center;gap:8px;padding:10px 15px;border:1px solid var(--line);border-radius:12px;background:#fff;color:var(--ink);text-decoration:none;box-shadow:0 7px 20px rgba(62,57,150,.06);transition:.22s ease}.top-btn:hover{transform:translateY(-2px);box-shadow:0 12px 25px rgba(62,57,150,.12);border-color:#c9c9ff}.top-btn:active{transform:translateY(0) scale(.98)}
  .wrap{max-width:1180px;margin:0 auto}.hero{text-align:center;margin-bottom:34px}.hero-icon{width:58px;height:58px;margin:0 auto 14px;border-radius:20px;display:grid;place-items:center;background:linear-gradient(135deg,#e9e9ff,#d9d5ff);font-size:28px;box-shadow:0 10px 28px rgba(86,104,255,.12)}h1{font-size:34px;line-height:1.15;margin:0 0 9px;letter-spacing:-.7px}.sub{margin:0;color:var(--muted);font-size:16px}.plans{display:grid;grid-template-columns:repeat(3,1fr);gap:24px;align-items:stretch}.plan-card{position:relative;background:rgba(255,255,255,.94);border:1px solid var(--line);border-radius:22px;padding:32px 28px 26px;box-shadow:0 13px 38px rgba(68,61,158,.08);transition:transform .25s ease,box-shadow .25s ease,border-color .25s ease}.plan-card:hover{transform:translateY(-7px);box-shadow:0 24px 48px rgba(68,61,158,.14);border-color:#cbc9ff}.plan-card.current{border:2px solid var(--a1);box-shadow:0 20px 44px rgba(86,104,255,.16)}.badge{position:absolute;top:-14px;left:50%;transform:translateX(-50%);padding:7px 18px;border-radius:999px;background:linear-gradient(90deg,var(--a1),var(--a2));color:#fff;font-weight:700;font-size:13px;box-shadow:0 8px 18px rgba(86,104,255,.24)}.plan-head{text-align:center}.plan-head h2{margin:4px 0 10px;font-size:22px}.price{font-size:35px;font-weight:800;letter-spacing:-.7px}.price small{font-size:14px;color:var(--muted);font-weight:500}.limit{margin:9px 0 20px;color:#66719a;font-size:14px;font-weight:600}.feature-title{font-size:13px;font-weight:800;text-transform:uppercase;letter-spacing:.7px;color:#5f6a91;margin:20px 0 12px}.features{list-style:none;padding:0;margin:0 0 25px;display:grid;gap:11px}.features li{display:flex;align-items:flex-start;gap:9px;color:#495577;font-size:14px;line-height:1.35}.check{width:20px;height:20px;flex:0 0 20px;border-radius:50%;display:grid;place-items:center;background:#e9f9ef;color:var(--green);font-size:12px;font-weight:800}.choose-btn{width:100%;padding:14px 16px;border:0;border-radius:13px;background:linear-gradient(90deg,var(--a1),var(--a2));color:#fff;font-weight:750;cursor:pointer;box-shadow:0 10px 23px rgba(86,104,255,.2);transition:.22s ease}.choose-btn:hover:not(:disabled){transform:translateY(-2px);box-shadow:0 15px 30px rgba(86,104,255,.28);filter:brightness(1.04)}.choose-btn:active:not(:disabled){transform:translateY(0) scale(.985)}.choose-btn:disabled{background:#e5e7f5;color:#8b91aa;cursor:not-allowed;box-shadow:none}.foot-note{text-align:center;color:var(--muted);font-size:13px;margin-top:28px}
  @media(max-width:900px){.plans{grid-template-columns:1fr}.topbar{align-items:flex-start}.top-actions{flex-wrap:wrap;justify-content:flex-end}}@media(max-width:560px){.es-page{padding:22px 16px 35px}.topbar{flex-direction:column}.top-actions{width:100%}.top-btn{flex:1;justify-content:center}.hero h1{font-size:28px}.plan-card{padding:28px 22px 23px}}
`;

const FALLBACK_FEATURES = {
  free: ['50 send credits every day', 'Basic email campaigns', 'Spreadsheet recipient import', '3-day trial'],
  pro: ['450 send credits every day', 'File attachments', 'CC / BCC support', 'Premium template designs', 'Priority upgrade access', 'Share quota across up to 2 email accounts'],
  business: ['1,000 send credits every day', 'File attachments', 'CC / BCC support', 'Premium template designs', 'Priority upgrade access', 'Share quota across up to 3 email accounts'],
};

export default function Upgrade(){
  const router=useRouter(); const [data,setData]=useState(null);
  useEffect(()=>{if(!router.isReady)return; (async()=>{const r=await fetch('/api/plan-status',{credentials:'same-origin'});if(r.ok)setData(await r.json());else setData(false)})()},[router.isReady]);
  const choose=(key)=>router.push(`/payment?plan=${encodeURIComponent(key)}`);
  return <><Head><title>Choose your plan</title></Head><style dangerouslySetInnerHTML={{__html:PAGE_CSS}}/><div className="es-page">
    <div className="topbar"><div className="brand"><img src="/assets/logo.png" alt="Email Sender"/><div className="brand-text"><h2>Email Sender</h2><p>Smart Email Automation</p></div></div><div className="top-actions"><a className="top-btn" href="/profile">👤 Profile</a><a className="top-btn" href="/campaign">← Back to campaign</a></div></div>
    <div className="wrap"><div className="hero"><div className="hero-icon">♛</div><h1>Choose your plan</h1><p className="sub">Upgrade your account to unlock more sending power and useful campaign features.</p></div>
      {data===false&&<div style={{textAlign:'center'}}>Please log in first.</div>}
      {data&&<div className="plans">{Object.entries(data.plans).map(([key,plan])=>{const current=key===data.currentPlan;const features=plan.displayFeatures||FALLBACK_FEATURES[key]||[];return <div key={key} className={`plan-card ${current?'current':''}`}>{current&&<span className="badge">Current plan</span>}<div className="plan-head"><h2>{plan.name}</h2><div className="price">{plan.priceRs?<>Rs {plan.priceRs.toLocaleString()}<small> /mo</small></>:'Free'}</div><div className="limit">{plan.dailyLimit.toLocaleString()} send credits / day</div></div><div className="feature-title">What you get</div><ul className="features">{features.map((f,i)=><li key={i}><span className="check">✓</span><span>{f}</span></li>)}</ul><button className="choose-btn" disabled={current||plan.priceRs===0} onClick={()=>choose(key)}>{current?'Active':plan.priceRs===0?'Free plan':'Choose this plan →'}</button></div>})}</div>}
      <div className="foot-note">Secure manual payment • No card required • Your account is upgraded after payment verification</div>
    </div></div></>;
}
